//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishLandApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oder()
        {
            this.OderProducts = new HashSet<OderProduct>();
        }
    
        public int OderID { get; set; }
        public string Status { get; set; }
        public string Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime Date { get; set; }
        public int AuthenticationID { get; set; }
    
        public virtual Authentication Authentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderProduct> OderProducts { get; set; }
    }
}
